version: "2"
services:

  moc-vr:
    image: quay.io/informaticslab/moc-vr:latest
    restart: always
    environment:
    - MOC_VR_AWS_ACCESS_KEY_ID=${MOC_VR_AWS_ACCESS_KEY_ID}
    - MOC_VR_AWS_SECRET_ACCESS_KEY=${MOC_VR_AWS_SECRET_ACCESS_KEY}
    - MOC_VR_OAUTH_CLIENT_ID=${MOC_VR_OAUTH_CLIENT_ID}
    - MOC_VR_OAUTH_CLIENT_SECRET=${MOC_VR_OAUTH_CLIENT_SECRET}
    - DOMAIN=${DOMAIN}
    - SESSION_SECRET=${SESSION_SECRET}
    ports:
    - 80:3000

  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
